### ISSUE TITLE
allow manual input of tags and keys

### ISSUE THREAD

**Issue by riccardoklinger** [riccardoklinger/OSMquery#16]
As working on a map for pumps in Berlin I added a tag to the key man_made in the config. It would be great to offer the user to define an own key/tag combination together with the predefined ones.

**Comment by rastrau** [comment]
True, but it also complicates the GUI more probably? Alternatively, we could adapt the contextual help text and explain to users a) that they can edit the config file themselves or b) (my preference) where they can submit new tag values (and potentially tag keys) to be included in the config file. 

We could even take this issue, https://github.com/riccardoklinger/OSMquery/issues/8 and https://github.com/riccardoklinger/OSMquery/issues/10 to create an expert version of the tool in the same toolbox, where users can enter custom (strictly Overpass compliant) query syntax. If we ever do this, we should modularise the code much more strongly so that both tools can both use the some functions.

What do you think?

**Comment by riccardoklinger** [comment]
I'm already working on this! I will create a second tool that simply takes the query as a string input.

**Comment by riccardoklinger** [comment]
I created the [OverpassQuery ](https://github.com/riccardoklinger/OSMquery/tree/OverpassQuery) branch for this. 
@rastrau  @michaelmgis please test and provide feedback. looks good to me, so I am ready for merge. commits from [customCRS ](https://github.com/riccardoklinger/OSMquery/tree/customCRS) branch should be merged first!

**Comment by riccardoklinger** [comment]
done: a3a076ba6a930e0307f3aab5b761199c068b6ba5

**Comment by rastrau** [comment]
@riccardoklinger: In the https://github.com/riccardoklinger/OSMquery/tree/OverpassQuery branch the expert tool does not seem to work for me in ArcGIS 10.5: Server Response `400` (`Bad Request`).

![image](https://user-images.githubusercontent.com/4510815/44920238-b1109900-ad3f-11e8-8b1d-eada3abdb103.png)

**Comment by riccardoklinger** [comment]
Yes, maybe change the default query to a response with a smaller dataset. This one will download all water pumps from around the world.

**Comment by riccardoklinger** [comment]
But I had several code 400 responses today...

**Comment by rastrau** [comment]
Yes, it might be a problem on the server-side. You can see that in my case the tool responded with the error very quickly, i.e. it's not the 25 secs timeout it's running into because of too much data.

**Comment by riccardoklinger** [comment]
No. It's worse: code 400 means, invalid request. Most likely the query is shite.

**Comment by rastrau** [comment]
Nice, the default query works now, thanks!
