### ISSUE TITLE
add field for featureClasses takes too long

### ISSUE THREAD

**Issue by riccardoklinger** [riccardoklinger/OSMquery#3]
there is the addFields function which takes an array of field descriptions as input. but I wasn't able to implement it yet.

**Comment by riccardoklinger** [comment]
http://pro.arcgis.com/en/pro-app/tool-reference/data-management/add-fields.htm

**Comment by riccardoklinger** [comment]
currently we iterate over all tags of a type (node, or way) and create a field for every tag.... this should use not n times the arcpy.AddField_management but only once the arcpy.management.AddFields

**Comment by rastrau** [comment]
If I'm not mistaken, using `arcpy.management.Add_Fields()` would break your compatibility with ArcGIS 10.x (as far as I know, this function is only available from ArcGIS Pro). However, looking at the code, an easy speed-up (albeit of uncertain impact) would be to make `Layer`s out of the feature classes before adding fields. If I remember correctly this pre-computes some tests *once* which would otherwise be carried out during every call of `AddField_management()`.

**Comment by rastrau** [comment]
This seems okay though, doesn't it. Closing this issue for now.
