### ISSUE TITLE
Support different (non-WGS 1984) coordinate reference systems (CRS) for output data sets

### ISSUE THREAD

**Issue by riccardoklinger** [riccardoklinger/OSMquery#7]
For the current mode the tool creates feature classes in 4326. I would love to see the option to create the FCs in the CRS of the current project instead.
What do others think?

**Comment by rastrau** [comment]
This would be valuable in my opinion.

I'm not quite sure how it would be implemented: You'd need to get the data frame's CRS, find candidate transformations between the data frame's SRS and EPSG:4326 and allow the user to pick the suitable transformation. I guess this is possible programmatically, but haven't implemented it before.

What is the expected behaviour if the data frame's CRS is undefined?

**Comment by riccardoklinger** [comment]
I would go with a siple checkbox: "use current project CRS" 
If the user selects it we will transform the coordinates of each node in the desired CRS. 
What do you think @rastrau ? I will create a branch for this. YOu can test then.

**Comment by rastrau** [comment]
I'm not sure we're talking about the same. In my second sentence ("taking data frame's CRS") I think I was addressing the idea that we should allow for non EPSG:4326 extent coordinates (that's in another issue). But the same mechanism applies here as well with respect to reprojecting the resulting feature layers from EPSG4326 to the project CRS: Depending on what CRS your project has, just reprojecting to this new target CRS is not enough – sometimes you need to choose the exact [transformation method](http://pro.arcgis.com/en/pro-app/tool-reference/data-management/project.htm) wisely (e.g. in the Swiss context). See also [here](https://www.esri.com/arcgis-blog/products/product/mapping/about-geographic-transformations-and-how-to-choose-the-right-one/).

I do not know, however, in what share of potential reprojections the user would need to pick a transformation because no default one is given or because the default one is bad.

Maybe I'm overthinking, but I see two options: 
- 'luxurious' one: allow the user to choose the transformation
- simpler one: make sure that we use that/those transformation(s) that the user potentially set in their data frame

**Comment by riccardoklinger** [comment]
I got your point. Are there "indicators" when a simple choice of a different CRS as proposed in branch customCRS might not be sufficient?
maybe drop an AddWarning inside the tool.
Currently the customCRS reproject the values from OSM (4326) to the desired CRS of your input. Default CRS for the output is still set to 4326. We could also define a warning prior query that the chosen CRS is shite as we don't use any cool transformations...

**Comment by rastrau** [comment]
I added this functionality In the branch `customCRS`, can you please check if you like the implemented behaviour?

I use `arcpy.ListTransformations(from_sr, to_sr)` to get a list and populate a new tool parameter with that. Using a parameter category, I hide this functionality a bit for now, as it further complicates the GUI (but I'm unsure if this is a good approach as it could be not familiar to most users). I newly allow for the custom CRS parameter to remain empty in which case all output defaults to EPSG:4326.

A downside of this functionality: If the data frame is in, for example, WGS 1984 (for example, for being able to select *Same as display*), the tool produces a warning about layers in the TOC having a different datum than the data frame. As far as I know, this warning cannot be suppressed (probably also shouldn't). If we allow for arbitrary CRS of the data frame also for extent input, this problem would likely disappear for most users, assuming the non-EPSG:4326 CRS of the data frame would probably be the same as the non-EPSG:4326 CRS they wish their output data to have.

**Comment by riccardoklinger** [comment]
My tests where positive as well. I would go with this and merge it! If user finds a bug in the logic they might open an issue and we can deal with it.

**Comment by riccardoklinger** [comment]
merged and commited in a3a076ba6a930e0307f3aab5b761199c068b6ba5
